### ISSUE TITLE
在块粘贴时遇到的问题.

### ISSUE THREAD

**Issue by qzd1989** [dofy/learn-vim#16]
ctrl+v,选中了多行,y后
移到需要粘贴的地方,但下面还有其他代码,这时如果用p,会把下面的代码与复制的内容合并起来(有点类似replace),我想在粘贴的时候把下面的代码依次往下移,怎么操作呢? 求教.

**Comment by dofy** [comment]
块选多行可以试试 shift+v

**Comment by qzd1989** [comment]
谢谢,果然解决了
