### ISSUE TITLE
English Version (translated by google translate: 英文版)

### ISSUE THREAD

**Issue by mateushnsoares** [dofy/learn-vim#19]
Add an English version.

Translated by google translate:

添加英文版本。

**Comment by dofy** [comment]
Yes, this's in my plan.

**Comment by dofy** [comment]
You can check out English version in this branch.

https://github.com/dofy/learn-vim/tree/en-us

**Comment by mateushnsoares** [comment]
Thanks for create an English version... PS.: I started.
