### ISSUE TITLE
进入 Ex mode 后如何退出？

### ISSUE THREAD

**Issue by byr-gdp** [dofy/learn-vim#5]
测试环境 Mac zsh

有种说法是输入 `visual` 可恢复，但测试效果是"分屏"，即屏幕右半部分回到了原来的文档内容，左半部分依旧是 Ex mode 的目录树。

尝试了发现 `:bd` 可以返回，但仅仅是我本地测试可以。
请教那种做法更好？

**Comment by dofy** [comment]
`:bd` 是个好方法

另外，如果没有进行过文件夹跳转，也可以用 `Ctrl-o` 返回。

**Comment by dofy** [comment]
**补充**

你说的 `visual` 是如何输入的？如果是指 Ex mode 中按 `v` 键，那应该不是指 `visual` 而是 `vsplit` 是在分屏中打开光标处文件。

**Comment by byr-gdp** [comment]
@dofy 对，我应该是触发了 vsplit。但同样测试了:visual，效果是开启了一个新的 buffer，而不是回到之前那个...

**Comment by dofy** [comment]
看了下 Netrw 的帮助，上网也找了一下，没找到退出的命令。
暂时看来 `:bd` 是最方便的了。
so, close this issue.
