### ISSUE TITLE
请问 md文件编码 是什么？

### ISSUE THREAD

**Issue by cuikangyuan** [dofy/learn-vim#6]
刚刚接触vim，在vps上安装vim，clone之后，vim打开文件发现中文出现类似于麻将块的乱码，使用putty登陆，请问怎么解决？

**Comment by byr-gdp** [comment]
如果没错的话应该是 utf-8

1. vim 中直接通过 `:set fileencoding` 可查看文件编码
2. 终端中 `file -I filename` 可看到 charset，即文件编码

**Comment by cuikangyuan** [comment]
好的 谢谢

**Comment by dofy** [comment]
@cuikangyuan 
第四章中提到的设置里（`.vimrc`）可以设置默认编码 `set encoding=utf-8`

**Comment by cuikangyuan** [comment]
好的@dofy
